# Generated by Django 4.1.5 on 2023-01-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=255)),
                ('prod_price', models.IntegerField(max_length=9000)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
