# Generated by Django 4.1.5 on 2023-01-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='image',
            field=models.ImageField(upload_to='kStore/templates/images/'),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='prod_price',
            field=models.IntegerField(),
        ),
    ]
