# Generated by Django 4.1.5 on 2023-01-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kStore', '0008_alter_producttable_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
    ]
